language: go

go:
 - 1.4

install:
 - wget https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.17.zip
 - unzip -q go_appengine_sdk_linux_amd64-1.9.17.zip
 - export PATH=$PATH:$PWD/go_appengine/

script:
 - goapp get code.google.com/p/google-api-go-client/googleapi/transport
 - goapp get code.google.com/p/google-api-go-client/plus/v1
 - goapp test
